"""Tech term constants used by the DOCX export pipeline.

Resume content is no longer generated by code in this app — the operator
pastes a ChatGPT-produced JSON in the Resumes tab and the backend renders
it via core.docx_resume_export. The only thing kept here is the tech-term
vocabulary used by the exporter for auto-bolding fallback when ChatGPT
forgets to emit <B>...</B> tags around tech keywords.
"""
from __future__ import annotations


KNOWN_TECH_TERMS: list[str] = [
    # Languages
    'Python', 'JavaScript', 'TypeScript', 'Java', 'Go', 'Rust', 'C#', 'C++', 'C', 'Ruby', 'PHP', 'Swift', 'Kotlin',
    'Scala', 'R', 'Bash', 'Shell', 'SQL', 'HTML', 'CSS', 'Solidity', 'Elixir', 'Clojure', 'Haskell', 'Dart', 'Lua',
    # Frontend
    'React', 'Next.js', 'Redux', 'React Query', 'Tailwind CSS', 'Material UI', 'Bootstrap', 'Storybook', 'Webpack', 'Vite',
    'Angular', 'Vue', 'Nuxt', 'Svelte', 'jQuery',
    # Backend
    'Node.js', 'Express', 'NestJS', 'FastAPI', 'Flask', 'Django', 'Spring Boot', 'ASP.NET Core', '.NET', 'Ruby on Rails',
    'Laravel', 'Phoenix', 'gRPC', 'GraphQL', 'Apollo GraphQL', 'Hibernate', 'Entity Framework', 'Prisma', 'SQLAlchemy',
    'RabbitMQ', 'Celery', 'REST API', 'WebSockets', 'Microservices', 'API Gateway',
    # Data / Databases
    'PostgreSQL', 'MySQL', 'SQL Server', 'SQLite', 'MongoDB', 'Redis', 'Elasticsearch', 'OpenSearch', 'Kafka', 'Snowflake',
    'dbt', 'Airflow', 'Spark', 'BigQuery', 'DynamoDB', 'Cassandra', 'ClickHouse', 'Redshift', 'Databricks',
    # Cloud / DevOps
    'AWS', 'Azure', 'GCP', 'Docker', 'Kubernetes', 'Helm', 'Terraform', 'GitHub Actions', 'GitLab CI', 'Jenkins', 'Argo CD',
    'Prometheus', 'Grafana', 'Datadog', 'Sentry', 'Nginx', 'Linux', 'Azure DevOps', 'Cloud Run', 'GKE', 'EKS', 'ECS', 'EC2',
    'S3', 'RDS', 'Lambda', 'CloudFront', 'IAM', 'Key Vault', 'Azure Functions', 'Ansible', 'Pulumi', 'Vagrant',
    'CI/CD', 'Infrastructure as Code', 'Load Balancing', 'Auto Scaling', 'Service Mesh', 'Istio',
    # Testing
    'Jest', 'Playwright', 'Cypress', 'React Testing Library', 'Pytest', 'JUnit', 'NUnit', 'Selenium', 'Postman',
    'Unit Testing', 'Integration Testing', 'End-to-End Testing', 'TDD', 'BDD', 'Mockito',
    # AI / ML
    'OpenAI API', 'LangChain', 'LlamaIndex', 'Pinecone', 'Weaviate', 'PyTorch', 'TensorFlow', 'Hugging Face',
    'scikit-learn', 'Pandas', 'NumPy', 'Jupyter', 'MLflow', 'RAG', 'Vector Database', 'LLM',
    'Web3.js', 'Ethers.js', 'Hardhat', 'Foundry', 'Truffle', 'Ganache', 'MetaMask',
    # Blockchain
    'Ethereum', 'Solana', 'Binance Smart Chain', 'Smart Contracts', 'DeFi', 'NFT', 'AMM',
    # Other tools
    'Stripe', 'Twilio', 'Socket.IO', 'Auth0', 'Okta', 'Splunk', 'New Relic', 'MCP', 'FastMCP',
    'Git', 'GitHub', 'GitLab', 'Jira', 'Confluence', 'Figma', 'Swagger', 'OpenAPI',
]
